//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saman.Backend.Share.shareValidators.Rsx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validators_Rsx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validators_Rsx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saman.Backend.Share.shareValidators.Rsx.Validators_Rsx", typeof(Validators_Rsx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید حداقل برای 3 سال قبل باشد..
        /// </summary>
        internal static string Validator_Birthdate {
            get {
                return ResourceManager.GetString("Validator_Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید بزرگتر از تاریخ جاری باشد..
        /// </summary>
        internal static string Validator_DateAfterNow {
            get {
                return ResourceManager.GetString("Validator_DateAfterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید قبل از تاریخ جاری باشد..
        /// </summary>
        internal static string Validator_DateBeforeNow {
            get {
                return ResourceManager.GetString("Validator_DateBeforeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل معتبر وارد کنید: {0}..
        /// </summary>
        internal static string Validator_Email {
            get {
                return ResourceManager.GetString("Validator_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} شامل مقادیر نامعتبر است. مقادیر نامعتبر عبارتند از: {1}..
        /// </summary>
        internal static string Validator_InvalidValues {
            get {
                return ResourceManager.GetString("Validator_InvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} اجباری است..
        /// </summary>
        internal static string Validator_Mandatory {
            get {
                return ResourceManager.GetString("Validator_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نمی‌تواند منفی باشد.
        /// </summary>
        internal static string Validator_NotNegative {
            get {
                return ResourceManager.GetString("Validator_NotNegative", resourceCulture);
            }
        }
    }
}
